In [1]:
import numpy as np;

m = np.array([[1,0,0], 
              [0,0,1],
              [1,0,0]]);

print(m.shape[0]);

dp = 1/m.shape[0];

print(dp);

sum_of_columns = np.sum(m, axis = 0);
print(sum_of_columns);


def insert_reciprocals(matrix):
    for i in range[0, matrix.shape[0]]:
        if i == 0:
        return i;
        else:
            i = 1/i;
            return i;
print(reciprocal(outgoing))


IndentationError: expected an indented block (<ipython-input-1-ff27073e5016>, line 20)

In [21]:
import numpy as np;

#create transition matrix for webpages

#default probability is equal for all webpages in the beginning
def default_probability(matrix):
    N = matrix.shape[0];
    default_p = 1/N;
    return default_p;

# create a matrix with the number of links to other webpages per link
def outgoing_links_matrix(matrix):
    outgoing = np.sum(matrix, axis = 0);
    return outgoing;

# calculation of page ranks with specified number of itertions
def page_rank(matrix, iterations):
    ranks = np.full(matrix.shape[0], default_probability(matrix));
    print(ranks);
    
    for i in range(0, interations):
        previous_ranks = ranks;
        for 
        ranks =  #new ranks
        
        
## default probability
## pagerank algorithm
##sort
##print

#sort pages according to page rank

#print page ranks


[0.5 0.5]


In [49]:
#Google’s PageRank Algorithm in Python
# https://dzenanhamzic.com/2016/12/21/googles-pagerank-algorithm-in-python/


# import some stuff
import numpy as np
import scipy as sc
import pandas as pd
from fractions import Fraction
 
# keep it clean and tidy
def float_format(vector, decimal):
    return np.round((vector).astype(np.float), decimals=decimal)
 
# we have 3 webpages and probability of landing to each one is 1/3
#(defaultProbability)
dp = Fraction(1,3)
 
# WWW matrix
M = np.matrix([[0,0,1],
        [Fraction(1,2),0,0],
        [Fraction(1,2),1,0]])
print('transitions:');
print(M);

E = np.zeros((3,3))
E[:] = dp
print('default probs:');
print(E);
 
# taxation
beta = 0.7
 
# WWW matrix
A = beta * M + ((1-beta) * E)
print('pr iteration:');
print(A);

# initial vector
r = np.matrix([dp, dp, dp])
r = np.transpose(r)

print(float_format(r,3))

previous_r = r
for it in range(1,100):
    r = A * r
    print(float_format(r,3))
    #check if converged
    if (previous_r==r).all():
        break
    previous_r = r
 
print("Final:\n", float_format(r,3))
print("sum", np.sum(r))

transitions:
[[0 0 1]
 [Fraction(1, 2) 0 0]
 [Fraction(1, 2) 1 0]]
default probs:
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
pr iteration:
[[0.1 0.1 0.7999999999999999]
 [0.44999999999999996 0.1 0.1]
 [0.44999999999999996 0.7999999999999999 0.1]]
[[0.333]
 [0.333]
 [0.333]]
[[0.333]
 [0.217]
 [0.45 ]]
[[0.415]
 [0.217]
 [0.368]]
[[0.358]
 [0.245]
 [0.397]]
[[0.378]
 [0.225]
 [0.397]]
[[0.378]
 [0.232]
 [0.39 ]]
[[0.373]
 [0.232]
 [0.395]]
[[0.376]
 [0.231]
 [0.393]]
[[0.375]
 [0.232]
 [0.393]]
[[0.375]
 [0.231]
 [0.394]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.23

In [ ]:
#tutorials point
# https://www.tutorialspoint.com/page-rank-algorithm-and-implementation-using-python


import numpy as np
import scipy as sc
import pandas as pd
from fractions import Fraction
def display_format(my_vector, my_decimal):
   return np.round((my_vector).astype(np.float), decimals=my_decimal)
my_dp = Fraction(1,3)
Mat = np.matrix([[0,0,1],
        [Fraction(1,2),0,0],
        [Fraction(1,2),1,0]])
Ex = np.zeros((3,3))
Ex[:] = my_dp
beta = 0.7
Al = beta * Mat + ((1-beta) * Ex)
r = np.matrix([my_dp, my_dp, my_dp])
r = np.transpose(r)
previous_r = r
for i in range(1,100):
   r = Al * r
   print (display_format(r,3))
   if (previous_r==r).all():
      break
   previous_r = r
print ("Final:\n", display_format(r,3))
print ("sum", np.sum(r))

In [ ]:
#Geeks for geeks
# 

def pagerank(G, alpha=0.85, personalization=None, 
            max_iter=100, tol=1.0e-6, nstart=None, weight='weight', 
            dangling=None): 
    """Return the PageRank of the nodes in the graph. 

    PageRank computes a ranking of the nodes in the graph G based on 
    the structure of the incoming links. It was originally designed as 
    an algorithm to rank web pages. 

    Parameters 
    ---------- 
    G : graph 
    A NetworkX graph. Undirected graphs will be converted to a directed 
    graph with two directed edges for each undirected edge. 

    alpha : float, optional 
    Damping parameter for PageRank, default=0.85. 

    personalization: dict, optional 
    The "personalization vector" consisting of a dictionary with a 
    key for every graph node and nonzero personalization value for each node. 
    By default, a uniform distribution is used. 

    max_iter : integer, optional 
    Maximum number of iterations in power method eigenvalue solver. 

    tol : float, optional 
    Error tolerance used to check convergence in power method solver. 

    nstart : dictionary, optional 
    Starting value of PageRank iteration for each node. 

    weight : key, optional 
    Edge data key to use as weight. If None weights are set to 1. 

    dangling: dict, optional 
    The outedges to be assigned to any "dangling" nodes, i.e., nodes without 
    any outedges. The dict key is the node the outedge points to and the dict 
    value is the weight of that outedge. By default, dangling nodes are given 
    outedges according to the personalization vector (uniform if not 
    specified). This must be selected to result in an irreducible transition 
    matrix (see notes under google_matrix). It may be common to have the 
    dangling dict to be the same as the personalization dict. 

    Returns 
    ------- 
    pagerank : dictionary 
    Dictionary of nodes with PageRank as value 

    Notes 
    ----- 
    The eigenvector calculation is done by the power iteration method 
    and has no guarantee of convergence. The iteration will stop 
    after max_iter iterations or an error tolerance of 
    number_of_nodes(G)*tol has been reached. 

    The PageRank algorithm was designed for directed graphs but this 
    algorithm does not check if the input graph is directed and will 
    execute on undirected graphs by converting each edge in the 
    directed graph to two edges. 


    """
    if len(G) == 0: 
        return {} 

    if not G.is_directed(): 
        D = G.to_directed() 
    else: 
        D = G 

    # Create a copy in (right) stochastic form 
    W = nx.stochastic_graph(D, weight=weight) 
    N = W.number_of_nodes() 

    # Choose fixed starting vector if not given 
    if nstart is None: 
        x = dict.fromkeys(W, 1.0 / N) 
    else: 
        # Normalized nstart vector 
        s = float(sum(nstart.values())) 
        x = dict((k, v / s) for k, v in nstart.items()) 

    if personalization is None: 

        # Assign uniform personalization vector if not given 
        p = dict.fromkeys(W, 1.0 / N) 
    else: 
        missing = set(G) - set(personalization) 
        if missing: 
            raise NetworkXError('Personalization dictionary '
                                'must have a value for every node. '
                                'Missing nodes %s' % missing) 
        s = float(sum(personalization.values())) 
        p = dict((k, v / s) for k, v in personalization.items()) 

    if dangling is None: 

        # Use personalization vector if dangling vector not specified 
        dangling_weights = p 
    else: 
        missing = set(G) - set(dangling) 
        if missing: 
            raise NetworkXError('Dangling node dictionary '
                                'must have a value for every node. '
                                'Missing nodes %s' % missing) 
        s = float(sum(dangling.values())) 
        dangling_weights = dict((k, v/s) for k, v in dangling.items()) 
    dangling_nodes = [n for n in W if W.out_degree(n, weight=weight) == 0.0] 

    # power iteration: make up to max_iter iterations 
    for _ in range(max_iter): 
        xlast = x 
        x = dict.fromkeys(xlast.keys(), 0) 
        danglesum = alpha * sum(xlast[n] for n in dangling_nodes) 
        for n in x: 

            # this matrix multiply looks odd because it is 
            # doing a left multiply x^T=xlast^T*W 
            for nbr in W[n]: 
                x[nbr] += alpha * xlast[n] * W[n][nbr][weight] 
            x[n] += danglesum * dangling_weights[n] + (1.0 - alpha) * p[n] 

        # check convergence, l1 norm 
        err = sum([abs(x[n] - xlast[n]) for n in x]) 
        if err < N*tol: 
            return x 
    raise NetworkXError('pagerank: power iteration failed to converge '
                        'in %d iterations.' % max_iter) 
